basic_app/urls.py
from django.urls import path
from . import views

# SET THE NAMESPACE!
app_name = 'basic_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls),
    path('special/', views.special,name='special'),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):


    user = models.OneToOneField(User, on_delete=models.CASCADE)


    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='basic_app/profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

basic_app/views.py
import django.shortcuts
from .forms import UserForm,UserProfileInfoForm

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return django.shortcuts.render(request, 'basic_app/index.html')

@login_required
def special(request):

    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):

    logout(request)

    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':


        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)


        if user_form.is_valid() and profile_form.is_valid():


            user = user_form.save()


            user.set_password(user.password)


            user.save()


            profile = profile_form.save(commit=False)


            profile.user = user


            if 'profile_pic' in request.FILES:
                print('found it')

                profile.profile_pic = request.FILES['profile_pic']


            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return django.shortcuts.render(request, 'basic_app/registration.html',
                                   {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied Please try Again.")

    else:
        #Nothing has been provided for username or password.
        return django.shortcuts.render(request, 'basic_app/login.html', {})

basic_app/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>HOME PAGE</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "basic_app/mystyle.css" %}"/>
    <style>
      body{
        background-image: url('{% static "basic_app/ml.jpg" %}');
      }
    </style>
  </head>
  <body >
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        {# Django Home Link / Admin Link / Register Link#}
        <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:register' %}">Register</a>

        {# Some logic on what to display for last item#}
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
        {% endif %}
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

basic_app/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="container">

    <h1></h1>
    {% if user.is_authenticated %}
        <h2 style="color:white">Welcome {{ user.username }},You are Logged In.</h2>
    {% else %}
        <h2 style="color:white">Welcome to the site!</h2>
    {% endif %}
  </div>

{% endblock %}

basic_app/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
  <div class="container">
    Please Login

        <form method="post" action="{% url 'basic_app:user_login' %}" style="margin-left:400px; color:#afe6bd;">
          {% csrf_token %}

          <label for="username">Username:</label></br>
          <input type="text" name="username" placeholder="Username" required></br>

          <label for="password">Password:</label></br>
          <input type="password" name="password" required></br>
          <p></p>
          <input type="submit" name="" value="Login" class="btn btn-dark"></br>
          <p></p>
          <a href="{% url 'basic_app:register' %}" class="btn btn-primary">Create New Account</a>
        </form>

  </div>
{% endblock %}

basic_app/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}


{% block body_block %}
  <div class="container">

      {% if registered %}
        <h1 style="color:white">Thank you for registering!</h1>
      {% else %}

       <h1 style="margin-top:100px; margin-left:400px; color:#9eb7d0">Register Here</h1>
       <h3 style="margin-left:400px;  color:#9eb7d0;">Just fill out the form.</h3>

       <form enctype="multipart/form-data" method="POST"style="margin-left:400px;color:#afe6bd">
         {% csrf_token %}
         <label for="id_username">Username:</label></br>
         <input class="input100" type="text" name="username" maxlength="150" required="" id="id_username"></br>
         <label for="id_email">Email address:</label></br>
          <input type="email" name="email" maxlength="254" id="id_email"></br>
         <label for="id_password">Password:</label></br>
         <input type="password" name="password" required="" id="id_password"></br>
         <p></p>
         <input type="submit" name="" value="Register" class="btn btn-dark">
       </form>







      {% endif %}

    </div>



{% endblock %}